#include "internal.h"
const char* VS_SOURCE = "#version 330 core\n"
    "layout (location = 0) in vec2 aPos;\n"
    "layout (location = 1) in vec2 aTexCoord;\n"
    "out vec2 TexCoord;\n"
    "uniform mat4 u_projection;\n"
    "uniform mat4 u_model;\n"
    "void main() {\n"
    " gl_Position = u_projection * u_model * vec4(aPos, 0.0, 1.0);\n"
    " TexCoord = aTexCoord;\n"
    "}\n";
const char* FS_SOURCE_YUV = "#version 330 core\n"
    "out vec4 FragColor;\n"
    "in vec2 TexCoord;\n"
    "uniform sampler2D tex_y;\n"
    "uniform sampler2D tex_u;\n"
    "uniform sampler2D tex_v;\n"
    "uniform float u_opacity;\n"
    "void main() {\n"
    " float y = texture(tex_y, TexCoord).r;\n"
    " float u = texture(tex_u, TexCoord).r - 0.5;\n"
    " float v = texture(tex_v, TexCoord).r - 0.5;\n"
    " float r = y + 1.402 * v;\n"
    " float g = y - 0.344136 * u - 0.714136 * v;\n"
    " float b = y + 1.772 * u;\n"
    " FragColor = vec4(r, g, b, u_opacity);\n"
    "}\n";
const char* FS_SOURCE_RGBA = "#version 330 core\n"
    "out vec4 FragColor;\n"
    "in vec2 TexCoord;\n"
    "uniform sampler2D tex_rgba;\n"
    "uniform float u_opacity;\n"
    "uniform bool u_flip_y;\n"
    "uniform bool u_premultiplied;\n"
    "void main() {\n"
    " vec2 uv = vec2(TexCoord.x, u_flip_y ? (1.0 - TexCoord.y) : TexCoord.y);\n"
    " vec4 color = texture(tex_rgba, uv);\n"
    " if (u_premultiplied) {\n"
    "   FragColor = vec4(color.rgb * u_opacity, color.a * u_opacity);\n"
    " } else {\n"
    "   FragColor = vec4(color.rgb, color.a * u_opacity);\n"
    " }\n"
    "}\n";
const char* FS_SOURCE_COLOR = "#version 330 core\n"
    "out vec4 FragColor;\n"
    "uniform vec4 u_color;\n"
    "void main() {\n"
    " FragColor = u_color;\n"
    "}\n";
const char* FS_SOURCE_COPY = "#version 330 core\n"
    "out vec4 FragColor;\n"
    "in vec2 TexCoord;\n"
    "uniform sampler2D u_texture;\n"
    "uniform float u_opacity;\n"
    "void main() {\n"
    " vec4 color = texture(u_texture, TexCoord);\n"
    " FragColor = color * u_opacity;\n"
    "}\n";
const char* FS_SOURCE_TINT = "#version 330 core\n"
    "out vec4 FragColor;\n"
    "in vec2 TexCoord;\n"
    "uniform sampler2D u_texture;\n"
    "uniform vec4 u_color;\n"
    "uniform float u_amount;\n"
    "void main() {\n"
    " vec4 src = texture(u_texture, TexCoord);\n"
    " float luminance = dot(src.rgb, vec3(0.299, 0.587, 0.114));\n"
    " vec3 tinted = luminance * u_color.rgb;\n"
    " FragColor = vec4(mix(src.rgb, tinted, u_amount), src.a);\n"
    "}\n";
const char* FS_SOURCE_FILL = "#version 330 core\n"
    "out vec4 FragColor;\n"
    "in vec2 TexCoord;\n"
    "uniform sampler2D u_texture;\n"
    "uniform vec4 u_color;\n"
    "uniform float u_amount;\n"
    "void main() {\n"
    " vec4 src = texture(u_texture, TexCoord);\n"
    " vec4 filled = vec4(u_color.rgb, src.a * u_color.a);\n"
    " FragColor = vec4(mix(src.rgb, filled.rgb, u_amount), mix(src.a, filled.a, u_amount));\n"
    "}\n";
const char* FS_SOURCE_GRADIENT_RAMP = "#version 330 core\n"
    "out vec4 FragColor;\n"
    "in vec2 TexCoord;\n"
    "uniform sampler2D u_texture;\n"
    "uniform vec2 u_start;\n"
    "uniform vec2 u_end;\n"
    "uniform vec4 u_start_color;\n"
    "uniform vec4 u_end_color;\n"
    "uniform float u_blend;\n"
    "void main() {\n"
    " vec4 src = texture(u_texture, TexCoord);\n"
    " vec2 dir = u_end - u_start;\n"
    " float len2 = max(dot(dir, dir), 0.00001);\n"
    " float t = clamp(dot(TexCoord - u_start, dir) / len2, 0.0, 1.0);\n"
    " vec4 grad = mix(u_start_color, u_end_color, t);\n"
    " vec3 base = src.a > 0.0001 ? (src.rgb / src.a) : vec3(0.0);\n"
    " float applied = clamp(u_blend * grad.a, 0.0, 1.0);\n"
    " vec3 rgb = mix(base, grad.rgb, applied);\n"
    " FragColor = vec4(rgb * src.a, src.a);\n"
    "}\n";
const char* FS_SOURCE_GRID = "#version 330 core\n"
    "out vec4 FragColor;\n"
    "in vec2 TexCoord;\n"
    "uniform sampler2D u_texture;\n"
    "uniform vec2 u_size;\n"
    "uniform float u_line_width;\n"
    "uniform vec4 u_color;\n"
    "uniform float u_opacity;\n"
    "void main() {\n"
    " vec4 src = texture(u_texture, TexCoord);\n"
    " vec2 cell = TexCoord * u_size;\n"
    " vec2 frac_part = fract(cell);\n"
    " float line = step(frac_part.x, u_line_width) + step(frac_part.y, u_line_width);\n"
    " line = clamp(line, 0.0, 1.0);\n"
    " vec4 grid = vec4(u_color.rgb, u_color.a * u_opacity * line);\n"
    " FragColor = vec4(mix(src.rgb, grid.rgb, grid.a), max(src.a, grid.a));\n"
    "}\n";
const char* FS_SOURCE_MOSAIC = "#version 330 core\n"
    "out vec4 FragColor;\n"
    "in vec2 TexCoord;\n"
    "uniform sampler2D u_texture;\n"
    "uniform float u_block_size;\n"
    "uniform vec2 u_resolution;\n"
    "uniform bool u_sharp_colors;\n"
    "void main() {\n"
    " float block = max(u_block_size, 1.0);\n"
    " vec2 frag_pixel = gl_FragCoord.xy - vec2(0.5);\n"
    " vec2 block_index = floor(frag_pixel / block);\n"
    " vec2 block_origin = block_index * block;\n"
    " vec2 sample_pixel_f = clamp(floor(block_origin + vec2(block * 0.5)), vec2(0.0), u_resolution - vec2(1.0));\n"
    " ivec2 sample_pixel = ivec2(sample_pixel_f);\n"
    " vec2 sample_uv = (sample_pixel_f + vec2(0.5)) / u_resolution;\n"
    " vec4 color = u_sharp_colors\n"
    "   ? texelFetch(u_texture, sample_pixel, 0)\n"
    "   : texture(u_texture, sample_uv);\n"
    " if (u_sharp_colors) {\n"
    "   color.rgb = floor(color.rgb * 255.0 + 0.5) / 255.0;\n"
    "   color.a = floor(color.a * 255.0 + 0.5) / 255.0;\n"
    " }\n"
    " FragColor = color;\n"
    "}\n";
const char* FS_SOURCE_BRIGHTNESS_CONTRAST = "#version 330 core\n"
    "out vec4 FragColor;\n"
    "in vec2 TexCoord;\n"
    "uniform sampler2D u_texture;\n"
    "uniform float u_brightness;\n"
    "uniform float u_contrast;\n"
    "void main() {\n"
    " vec4 src = texture(u_texture, TexCoord);\n"
    " vec3 color = src.rgb + vec3(u_brightness);\n"
    " color = (color - 0.5) * u_contrast + 0.5;\n"
    " FragColor = vec4(color, src.a);\n"
    "}\n";
const char* FS_SOURCE_BLUR = "#version 330 core\n"
    "out vec4 FragColor;\n"
    "in vec2 TexCoord;\n"
    "uniform sampler2D u_texture;\n"
    "uniform vec2 u_texel_size;\n"
    "uniform float u_radius;\n"
    "uniform vec2 u_direction;\n"
    "void main() {\n"
    " vec4 src = texture(u_texture, TexCoord);\n"
    " if (u_radius <= 0.001) { FragColor = src; return; }\n"
    " vec2 stepv = u_direction * u_texel_size * max(u_radius, 1.0);\n"
    " vec4 sum = src * 0.2270270270;\n"
    " sum += texture(u_texture, TexCoord + stepv * 1.3846153846) * 0.3162162162;\n"
    " sum += texture(u_texture, TexCoord - stepv * 1.3846153846) * 0.3162162162;\n"
    " sum += texture(u_texture, TexCoord + stepv * 3.2307692308) * 0.0702702703;\n"
    " sum += texture(u_texture, TexCoord - stepv * 3.2307692308) * 0.0702702703;\n"
    " FragColor = sum;\n"
    "}\n";
const char* FS_SOURCE_GLOW = "#version 330 core\n"
    "out vec4 FragColor;\n"
    "in vec2 TexCoord;\n"
    "uniform sampler2D u_texture;\n"
    "uniform vec2 u_texel_size;\n"
    "uniform float u_radius;\n"
    "uniform float u_intensity;\n"
    "uniform float u_threshold;\n"
    "uniform float u_softness;\n"
    "uniform vec4 u_color;\n"
    "uniform int u_mode;\n"
    "float luminance(vec3 c) {\n"
    " return dot(c, vec3(0.299, 0.587, 0.114));\n"
    "}\n"
    "vec4 samplePremult(vec2 uv) {\n"
    " return texture(u_texture, clamp(uv, vec2(0.0), vec2(1.0)));\n"
    "}\n"
    "vec4 downsample13(bool prefilter) {\n"
    " vec2 x = vec2(u_texel_size.x, 0.0);\n"
    " vec2 y = vec2(0.0, u_texel_size.y);\n"
    " vec4 a = samplePremult(TexCoord - 2.0*x + 2.0*y);\n"
    " vec4 b = samplePremult(TexCoord + 0.0*x + 2.0*y);\n"
    " vec4 c = samplePremult(TexCoord + 2.0*x + 2.0*y);\n"
    " vec4 d = samplePremult(TexCoord - 2.0*x + 0.0*y);\n"
    " vec4 e = samplePremult(TexCoord);\n"
    " vec4 f = samplePremult(TexCoord + 2.0*x + 0.0*y);\n"
    " vec4 g = samplePremult(TexCoord - 2.0*x - 2.0*y);\n"
    " vec4 h = samplePremult(TexCoord + 0.0*x - 2.0*y);\n"
    " vec4 i = samplePremult(TexCoord + 2.0*x - 2.0*y);\n"
    " vec4 j = samplePremult(TexCoord - x + y);\n"
    " vec4 k = samplePremult(TexCoord + x + y);\n"
    " vec4 l = samplePremult(TexCoord - x - y);\n"
    " vec4 m = samplePremult(TexCoord + x - y);\n"
    " vec4 down = e * 0.125;\n"
    " down += (a + c + g + i) * 0.03125;\n"
    " down += (b + d + f + h) * 0.0625;\n"
    " down += (j + k + l + m) * 0.125;\n"
    " if (!prefilter) return down;\n"
    " vec3 base = down.a > 0.00001 ? (down.rgb / down.a) : vec3(0.0);\n"
    " float knee = max(u_softness, 0.0001);\n"
    " float t = smoothstep(u_threshold - knee, u_threshold + knee, luminance(base));\n"
    " vec3 tint = mix(vec3(1.0), u_color.rgb, clamp(u_color.a, 0.0, 1.0));\n"
    " return vec4(down.rgb * tint * t, down.a * t);\n"
    "}\n"
    "vec4 upsampleTent() {\n"
    " vec2 o = u_texel_size * max(u_radius, 0.5);\n"
    " vec4 sum = vec4(0.0);\n"
    " sum += samplePremult(TexCoord + vec2(-o.x, -o.y));\n"
    " sum += samplePremult(TexCoord + vec2( 0.0, -o.y)) * 2.0;\n"
    " sum += samplePremult(TexCoord + vec2( o.x, -o.y));\n"
    " sum += samplePremult(TexCoord + vec2(-o.x,  0.0)) * 2.0;\n"
    " sum += samplePremult(TexCoord) * 4.0;\n"
    " sum += samplePremult(TexCoord + vec2( o.x,  0.0)) * 2.0;\n"
    " sum += samplePremult(TexCoord + vec2(-o.x,  o.y));\n"
    " sum += samplePremult(TexCoord + vec2( 0.0,  o.y)) * 2.0;\n"
    " sum += samplePremult(TexCoord + vec2( o.x,  o.y));\n"
    " return sum / 16.0;\n"
    "}\n"
    "void main() {\n"
    " vec4 color;\n"
    " if (u_mode == 0) color = downsample13(true);\n"
    " else if (u_mode == 1) color = downsample13(false);\n"
    " else color = upsampleTent();\n"
    " FragColor = color * u_intensity;\n"
    "}\n";
const char* FS_SOURCE_FRACTAL_NOISE = "#version 330 core\n"
    "out vec4 FragColor;\n"
    "in vec2 TexCoord;\n"
    "uniform sampler2D u_texture;\n"
    "uniform vec2 u_resolution;\n"
    "uniform float u_scale;\n"
    "uniform float u_evolution;\n"
    "uniform float u_contrast;\n"
    "uniform float u_brightness;\n"
    "uniform float u_octaves;\n"
    "uniform float u_amount;\n"
    "uniform vec2 u_offset;\n"
    "uniform bool u_invert;\n"
    "mat2 rot2(float a) {\n"
    " float c = cos(a);\n"
    " float s = sin(a);\n"
    " return mat2(c, -s, s, c);\n"
    "}\n"
    "float hash3(vec3 p) {\n"
    " return fract(sin(dot(p, vec3(127.1, 311.7, 191.999))) * 43758.5453123);\n"
    "}\n"
    "float noise3(vec3 p) {\n"
    " vec3 i = floor(p);\n"
    " vec3 f = fract(p);\n"
    " vec3 u = f * f * (3.0 - 2.0 * f);\n"
    " float n000 = hash3(i + vec3(0.0, 0.0, 0.0));\n"
    " float n100 = hash3(i + vec3(1.0, 0.0, 0.0));\n"
    " float n010 = hash3(i + vec3(0.0, 1.0, 0.0));\n"
    " float n110 = hash3(i + vec3(1.0, 1.0, 0.0));\n"
    " float n001 = hash3(i + vec3(0.0, 0.0, 1.0));\n"
    " float n101 = hash3(i + vec3(1.0, 0.0, 1.0));\n"
    " float n011 = hash3(i + vec3(0.0, 1.0, 1.0));\n"
    " float n111 = hash3(i + vec3(1.0, 1.0, 1.0));\n"
    " float nx00 = mix(n000, n100, u.x);\n"
    " float nx10 = mix(n010, n110, u.x);\n"
    " float nx01 = mix(n001, n101, u.x);\n"
    " float nx11 = mix(n011, n111, u.x);\n"
    " float nxy0 = mix(nx00, nx10, u.y);\n"
    " float nxy1 = mix(nx01, nx11, u.y);\n"
    " return mix(nxy0, nxy1, u.z);\n"
    "}\n"
    "float fbm(vec2 p, float octaves, float evolution) {\n"
    " float value = 0.0;\n"
    " float amplitude = 0.5;\n"
    " float total = 0.0;\n"
    " float z = evolution * 0.18;\n"
    " for (int i = 0; i < 6; i++) {\n"
    "   if (float(i) >= octaves) break;\n"
    "   value += noise3(vec3(p, z + float(i) * 3.17)) * amplitude;\n"
    "   total += amplitude;\n"
    "   p = rot2(0.35 + float(i) * 0.17) * (p * 2.0) + vec2(13.1, 7.9);\n"
    "   z = z * 1.91 + 2.37;\n"
    "   amplitude *= 0.5;\n"
    " }\n"
    " return total > 0.0 ? value / total : noise3(vec3(p, z));\n"
    "}\n"
    "void main() {\n"
    " vec4 src = texture(u_texture, TexCoord);\n"
    " float scale = max(u_scale, 1.0);\n"
    " float octaves = clamp(floor(u_octaves + 0.5), 1.0, 6.0);\n"
    " vec2 p = ((TexCoord * u_resolution) + u_offset) / scale;\n"
    " float n = fbm(p, octaves, u_evolution);\n"
    " n = (n - 0.5) * max(u_contrast, 0.0) + 0.5 + u_brightness;\n"
    " n = clamp(n, 0.0, 1.0);\n"
    " if (u_invert) n = 1.0 - n;\n"
    " vec3 noise_color = vec3(n);\n"
    " FragColor = vec4(mix(src.rgb, noise_color, clamp(u_amount, 0.0, 1.0)), src.a);\n"
    "}\n";
const char* FS_SOURCE_DISPLACEMENT_MAP = "#version 330 core\n"
    "out vec4 FragColor;\n"
    "in vec2 TexCoord;\n"
    "uniform sampler2D u_texture;\n"
    "uniform sampler2D u_map_texture;\n"
    "uniform vec2 u_resolution;\n"
    "uniform float u_scale_x;\n"
    "uniform float u_scale_y;\n"
    "uniform float u_amount;\n"
    "uniform vec2 u_offset;\n"
    "uniform int u_horizontal_channel;\n"
    "uniform int u_vertical_channel;\n"
    "uniform bool u_use_luma;\n"
    "float channelValue(vec4 c, int channel) {\n"
    " if (channel == 0) return c.r;\n"
    " if (channel == 1) return c.g;\n"
    " if (channel == 2) return c.b;\n"
    " if (channel == 3) return c.a;\n"
    " return dot(c.rgb, vec3(0.299, 0.587, 0.114));\n"
    "}\n"
    "void main() {\n"
    " vec2 map_uv = clamp(TexCoord + u_offset / u_resolution, vec2(0.0), vec2(1.0));\n"
    " vec4 map = texture(u_map_texture, map_uv);\n"
    " vec2 disp;\n"
    " if (u_use_luma) {\n"
    "   float l = channelValue(map, 4) - 0.5;\n"
    "   disp = vec2(l * u_scale_x, l * u_scale_y);\n"
    " } else {\n"
    "   float hx = channelValue(map, u_horizontal_channel) - 0.5;\n"
    "   float vy = channelValue(map, u_vertical_channel) - 0.5;\n"
    "   disp = vec2(hx * u_scale_x, vy * u_scale_y);\n"
    " }\n"
    " vec2 uv = clamp(TexCoord + (disp * u_amount) / u_resolution, vec2(0.0), vec2(1.0));\n"
    " FragColor = texture(u_texture, uv);\n"
    "}\n";
const char* FS_SOURCE_POSTERIZE = "#version 330 core\n"
    "out vec4 FragColor;\n"
    "in vec2 TexCoord;\n"
    "uniform sampler2D u_texture;\n"
    "uniform float u_levels;\n"
    "uniform float u_amount;\n"
    "void main() {\n"
    " vec4 src = texture(u_texture, TexCoord);\n"
    " float levels = max(floor(u_levels + 0.5), 2.0);\n"
    " vec3 post = floor(src.rgb * (levels - 1.0) + 0.5) / (levels - 1.0);\n"
    " FragColor = vec4(mix(src.rgb, post, clamp(u_amount, 0.0, 1.0)), src.a);\n"
    "}\n";
const char* FS_SOURCE_ADJUSTMENT_COMPOSITE = "#version 330 core\n"
    "out vec4 FragColor;\n"
    "in vec2 TexCoord;\n"
    "uniform sampler2D u_base_texture;\n"
    "uniform sampler2D u_adjusted_texture;\n"
    "uniform sampler2D u_mask_texture;\n"
    "uniform vec2 u_region_center;\n"
    "uniform vec2 u_region_half_size;\n"
    "uniform vec2 u_canvas_size;\n"
    "uniform float u_opacity;\n"
    "uniform float u_feather;\n"
    "uniform float u_region_rotation;\n"
    "uniform int u_blend_mode;\n"
    "uniform int u_mask_mode;\n"
    "uniform bool u_whole_frame;\n"
    "uniform bool u_has_mask;\n"
    "uniform bool u_mask_invert;\n"
    "float overlay_channel(float b, float s) {\n"
    " return b < 0.5 ? (2.0 * b * s) : (1.0 - 2.0 * (1.0 - b) * (1.0 - s));\n"
    "}\n"
    "vec3 blend_color(vec3 base, vec3 src, int mode) {\n"
    " if (mode == 1) return base + src;\n"
    " if (mode == 2) return base * src;\n"
    " if (mode == 3) return 1.0 - (1.0 - base) * (1.0 - src);\n"
    " if (mode == 4) return vec3(overlay_channel(base.r, src.r), overlay_channel(base.g, src.g), overlay_channel(base.b, src.b));\n"
    " return src;\n"
    "}\n"
    "void main() {\n"
    " vec4 base = texture(u_base_texture, TexCoord);\n"
    " vec4 adjusted = texture(u_adjusted_texture, TexCoord);\n"
    " float region_alpha = 1.0;\n"
    " if (!u_whole_frame) {\n"
    "   vec2 pixel = TexCoord * u_canvas_size;\n"
    "   float rad = radians(-u_region_rotation);\n"
    "   mat2 rot = mat2(cos(rad), -sin(rad), sin(rad), cos(rad));\n"
    "   vec2 local = rot * (pixel - u_region_center);\n"
    "   vec2 edge = u_region_half_size - abs(local);\n"
    "   float min_edge = min(edge.x, edge.y);\n"
    "   if (u_feather > 0.001) {\n"
    "     region_alpha = clamp(min_edge / u_feather, 0.0, 1.0);\n"
    "   } else {\n"
    "     region_alpha = min_edge >= 0.0 ? 1.0 : 0.0;\n"
    "   }\n"
    " }\n"
    " float mask_alpha = 1.0;\n"
    " if (u_has_mask) {\n"
    "   vec4 mask = texture(u_mask_texture, TexCoord);\n"
    "   mask_alpha = u_mask_mode == 1 ? dot(mask.rgb, vec3(0.299, 0.587, 0.114)) : mask.a;\n"
    "   if (u_mask_invert) mask_alpha = 1.0 - mask_alpha;\n"
    " }\n"
    " float alpha = clamp(adjusted.a * u_opacity * region_alpha * mask_alpha, 0.0, 1.0);\n"
    " vec3 blended = blend_color(base.rgb, adjusted.rgb, u_blend_mode);\n"
    " vec3 out_rgb = mix(base.rgb, clamp(blended, 0.0, 1.0), alpha);\n"
    " FragColor = vec4(out_rgb, max(base.a, alpha));\n"
    "}\n";
const char* VS_SCREEN = "#version 330 core\n"
    "layout (location = 0) in vec2 aPos;\n"
    "layout (location = 1) in vec2 aTexCoord;\n"
    "out vec2 TexCoord;\n"
    "void main() {\n"
    " gl_Position = vec4(aPos.x * 2.0 - 1.0, 1.0 - aPos.y * 2.0, 0.0, 1.0);\n"
    " TexCoord = vec2(aTexCoord.x, 1.0 - aTexCoord.y);\n"
    "}\n";
const char* FS_SCREEN = "#version 330 core\n"
    "out vec4 FragColor;\n"
    "in vec2 TexCoord;\n"
    "uniform sampler2D screenTexture;\n"
    "void main() {\n"
    " FragColor = texture(screenTexture, TexCoord);\n"
    "}\n";
const char* FS_SOURCE_TEXT = "#version 330 core\n"
    "in vec2 TexCoord;\n"
    "out vec4 FragColor;\n"
    "uniform sampler2D textAtlas;\n"
    "uniform vec4 u_color;\n"
    "uniform vec4 u_uv_rect;\n" // xy=top-left, zw=bottom-right
    "void main() {\n"
    " vec2 uv = mix(u_uv_rect.xy, u_uv_rect.zw, TexCoord);\n"
    " float alpha = texture(textAtlas, uv).r;\n"
    " float out_a = alpha * u_color.a;\n"
    " FragColor = vec4(u_color.rgb * out_a, out_a);\n"
    "}\n";
